### ISSUE TITLE
KeyNotFoundException

### ISSUE THREAD

**Issue by nordseth** [nordseth/Nibbler#19]
```
exception: System.Collections.Generic.KeyNotFoundException: The given key 'service' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key) in /_/src/System.Private.CoreLib/shared/System/Collections/Generic/Dictionary.cs:line 221
   at Nibbler.Utils.AuthenticationHandler.TrySetOAuth(String parameter) in C:\Projects\Nibbler\Nibbler\Utils\AuthenticationHandler.cs:line 86
```

Happens in a jenkins build running in openshift with a openshift registry.

**Comment by nordseth** [comment]
fixed in 1.1.0-beta.2
